import { type Voice, VoiceQuality } from 'expo-speech';

const voices: Array<[string, string, string]> = [
  ['BV074_streaming', 'Cô gái hoạt ngôn', 'vi'],
  ['BV421_vivn_streaming', 'Cô gái ngọt ngào', 'vi'],
  ['BV075_streaming', 'Thanh niên tự tin', 'vi'],
  ['vi_female_huong', 'Giọng nữ phổ thông', 'vi'],
  ['en_us_002', 'Jessie', 'en'],
  ['en_male_jomboy', 'Game On', 'en'],
  ['en_male_funny', 'Wacky', 'en'],
  ['en_us_ghostface', 'Scream', 'en'],
  ['en_female_samc', 'Empathetic', 'en'],
  ['en_male_cody', 'Serious', 'en'],
  ['en_female_makeup', 'Beauty Guru', 'en'],
  ['en_female_richgirl', 'Bestie', 'en'],
  ['en_male_grinch', 'Trickster', 'en'],
  ['en_us_006', 'Joey', 'en'],
  ['en_male_narration', 'Story Teller', 'en'],
  ['en_male_deadpool', 'Mr. GoodGuy', 'en'],
  ['en_uk_001', 'Narrator', 'en'],
  ['en_uk_003', 'Male English UK', 'en'],
  ['en_au_001', 'Metro', 'en'],
  ['en_male_jarvis', 'Alfred', 'en'],
  ['en_male_ashmagic', 'ashmagic', 'en'],
  ['en_male_olantekkers', 'olantekkers', 'en'],
  ['en_male_ukneighbor', 'Lord Cringe', 'en'],
  ['en_male_ukbutler', 'Mr. Meticulous', 'en'],
  ['en_female_shenna', 'Debutante', 'en'],
  ['en_female_pansino', 'Varsity', 'en'],
  ['en_male_trevor', 'Marty', 'en'],
  ['en_female_f08_twinkle', 'Pop Lullaby', 'en'],
  ['en_male_m03_classical', 'Classic Electric', 'en'],
  ['en_female_betty', 'Bae', 'en'],
  ['en_male_cupid', 'Cupid', 'en'],
  ['en_female_grandma', 'Granny', 'en'],
  ['en_male_m2_xhxs_m03_christmas', 'Cozy', 'en'],
  ['en_male_santa_narration', 'Author', 'en'],
  ['en_male_sing_deep_jingle', 'Caroler', 'en'],
  ['en_male_santa_effect', 'Santa', 'en'],
  ['en_female_ht_f08_newyear', 'NYE 2023', 'en'],
  ['en_male_wizard', 'Magician', 'en'],
  ['en_female_ht_f08_halloween', 'Opera', 'en'],
  ['en_female_ht_f08_glorious', 'Euphoric', 'en'],
  ['en_male_sing_funny_it_goes_up', 'Hypetrain', 'en'],
  ['en_female_ht_f08_wonderful_world', 'Melodrama', 'en'],
  ['en_male_m2_xhxs_m03_silly', 'Quirky Time', 'en'],
  ['en_female_emotional', 'Peaceful', 'en'],
  ['en_male_m03_sunshine_soon', 'Toon Beat', 'en'],
  ['en_female_f08_warmy_breeze', 'Open Mic', 'en'],
  ['en_male_m03_lobby', 'Jingle', 'en'],
  ['en_male_sing_funny_thanksgiving', 'Thanksgiving', 'en'],
  ['en_female_f08_salut_damour', 'Cottagecore', 'en'],
  ['en_us_007', 'Professor', 'en'],
  ['en_us_009', 'Scientist', 'en'],
  ['en_us_010', 'Confidence', 'en'],
  ['en_au_002', 'Smooth', 'en'],
  ['en_us_chewbacca', 'Chewbacca', 'en'],
  ['en_us_c3po', 'C3PO', 'en'],
  ['en_us_stitch', 'Stitch', 'en'],
  ['en_us_stormtrooper', 'Stormtrooper', 'en'],
  ['en_us_rocket', 'Rocket', 'en'],
  ['en_female_madam_leota', 'Madame Leota', 'en'],
  ['en_male_ghosthost', 'Ghost Host', 'en'],
  ['en_male_pirate', 'Pirate', 'en'],
  ['fr_001', 'French - Male 1', 'fr'],
  ['fr_002', 'French - Male 2', 'fr'],
  ['es_002', 'Spanish (Spain) - Male', 'es'],
  ['es_mx_002', 'Spanish MX - Male', 'es'],
  ['br_001', 'Portuguese BR - Female 1', 'pt'],
  ['br_003', 'Portuguese BR - Female 2', 'pt'],
  ['br_004', 'Portuguese BR - Female 3', 'pt'],
  ['br_005', 'Portuguese BR - Male', 'pt'],
  ['bp_female_ivete', 'Ivete Sangalo', 'pt'],
  ['bp_female_ludmilla', 'Ludmilla', 'pt'],
  ['pt_female_lhays', 'Lhays Macedo', 'pt'],
  ['pt_female_laizza', 'Laizza', 'pt'],
  ['pt_male_bueno', 'Galvão Bueno', 'pt'],
  ['de_001', 'German - Female', 'de'],
  ['de_002', 'German - Male', 'de'],
  ['id_001', 'Indonesian - Female', 'id'],
  ['jp_001', 'Japanese - Female 1', 'ja'],
  ['jp_003', 'Japanese - Female 2', 'ja'],
  ['jp_005', 'Japanese - Female 3', 'ja'],
  ['jp_006', 'Japanese - Male', 'ja'],
  ['jp_female_fujicochan', 'りーさ', 'ja'],
  ['jp_female_hasegawariona', '世羅鈴', 'ja'],
  ['jp_male_keiichinakano', 'Morio’s Kitchen', 'ja'],
  ['jp_female_oomaeaika', '夏絵ココ', 'ja'],
  ['jp_male_yujinchigusa', '低音ボイス', 'ja'],
  ['jp_female_shirou', '四郎', 'ja'],
  ['jp_male_tamawakazuki', '玉川寿紀', 'ja'],
  ['jp_female_kaorishoji', '庄司果織', 'ja'],
  ['jp_female_yagishaki', '八木沙季', 'ja'],
  ['jp_male_hikakin', 'ヒカキン', 'ja'],
  ['jp_female_rei', '丸山礼', 'ja'],
  ['jp_male_shuichiro', '修一朗', 'ja'],
  ['jp_male_matsudake', 'マツダ家の日常', 'ja'],
  ['jp_female_machikoriiita', 'まちこりーた', 'ja'],
  ['jp_male_matsuo', 'モジャオ', 'ja'],
  ['jp_male_osada', 'モリスケ', 'ja'],
  ['kr_002', 'Korean - Male 1', 'ko'],
  ['kr_003', 'Korean - Female', 'ko'],
  ['kr_004', 'Korean - Male 2', 'ko'],
];

export const TIKTOK_VOICES: Voice[] = voices.map(
  ([identifier, name, language]) => ({
    identifier,
    language,
    name,
    quality: VoiceQuality.Default,
  }),
);

export const isTikTokVoice = (voice?: Voice): boolean =>
  Boolean(
    voice?.identifier &&
      TIKTOK_VOICES.some(item => item.identifier === voice.identifier),
  );
